name: CI

on:
  push:
    branches:
      - '*'
    tags:
      - v*
  pull_request:
  workflow_dispatch:
  repository_dispatch:
    types: [run_build]

jobs:
  build:
    runs-on: ubuntu-latest
    container: ps2dev/ps2dev:latest
    steps:
    - name: Install dependencies
      run: |
        apk add build-base git bash p7zip

    - name: Workaround permission issue
      run: |
        git config --global --add safe.directory "$GITHUB_WORKSPACE"

    - uses: actions/checkout@v2
    - run: |
        git fetch --prune --unshallow

    - name: Compile project
      run: |
        make clean elfloader all package

    - name: Upload artifacts
      if: ${{ success() }}
      uses: actions/upload-artifact@v2
      with:
        name: POPSLDR
        path: POPSLoader.7z
 
    - name: Create pre-release
      if: github.ref == 'refs/heads/main'
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        title: "Development build"
        files: |
               Enceladus.tar.gz

    - name: Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: Enceladus.tar.gz
        tag_name: ${{ steps.tag.outputs.VERSION }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
